server {
    listen 80;
    server_name _;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    location / {
        return 200 'Pocket-TTS is running.\n';
        add_header Content-Type text/plain;
    }
    

    # Pocket-TTS API
    location /gen/ {
        proxy_pass http://pocket-tts:8000/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Generated MP3 files
    location /output/ {
        alias /usr/share/nginx/html/output/;

        add_header Cache-Control "public, max-age=31536000, immutable";
        expires 1y;

        open_file_cache max=100000 inactive=30s;
        open_file_cache_valid 120s;
        open_file_cache_min_uses 2;
        open_file_cache_errors on;

        access_log off;
        try_files $uri =404;
    }
}
